### ISSUE TITLE
works 

### ISSUE THREAD

**Issue by koendv** [josuah/uf2-utils#1]
Thank you for these tools. For ubuntu had to drop the --std=c99: 
```
diff --git a/Makefile b/Makefile
index 8920b9c..43c20fe 100644
--- a/Makefile
+++ b/Makefile
@@ -1,4 +1,4 @@
-CFLAGS = -Wall -Wextra -std=c99 -pedantic
+CFLAGS = -Wall -Wextra -pedantic
 PREFIX = /usr/local
 LDFLAGS =
 ```
else gcc complains: [typescript.txt](https://github.com/user-attachments/files/16176454/typescript.txt)

**Comment by josuah** [comment]
Hello! I forgot to close that fork. I added this commit in this repo to help with that:
https://github.com/tinyvision-ai-inc/uf2-utils/commit/3ca6d147efad7e3bcc099805e923e60102d0394b

Thank you very much for reporting!

**Comment by josuah** [comment]
Good to know.

**Comment by koendv** [comment]
I see you are into Lattice fpga's?

I'd like to share this open source project for an arm debugger:
https://orbcode.org/orbtrace-mini/
"orbtrace mini" uses a Lattice ECP5 to capture arm execution flow as it
happens. Sources are here:
https://github.com/orbcode/orbuculum
"orbtrace mini" has an external sram, but (last time I looked) the sram wasn't used yet.

best,

koen

**Comment by josuah** [comment]
That is a nice project. There might need some porting from the FPGA-centric design to an MCU/FPGA combined tool
https://github.com/orbcode/orbtrace_hw/blob/main/hw/orbtrace_mini/orbtrace_mini_v1_0.pdf

There is no input protection on the pico-ice like in orbtrace, but that could be some extra PMOD eventually.

There is a serial RAM for storage, but not HyperRAM, so would likely be a lower-end lower-perf project out of the pico-ice.
This might also work with a few equivalent boards around also featuring an iCE40 and RP2040.
